//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitaplar
    {
        public int ID { get; set; }
        public string barkod_no { get; set; }
        public string kitap_adi { get; set; }
        public string yazar_adi { get; set; }
        public string yayin_evi { get; set; }
        public string kitap_turu { get; set; }
        public string temin_bicimi { get; set; }
        public Nullable<System.DateTime> temin_tarihi { get; set; }
        public int stok_sayisi { get; set; }
        public byte[] resim { get; set; }
        public string dosyayolu { get; set; }
    }
}
