//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneTakipSistemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class kutuphaneEntities : DbContext
    {
        public kutuphaneEntities()
            : base("name=kutuphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kisiler> kisilers { get; set; }
        public virtual DbSet<kitaplar> kitaplars { get; set; }
        public virtual DbSet<emanetkitaplar> emanetkitaplars { get; set; }
    
        public virtual int kitapekleme(string barkod, string kitap_adi, string yazar_adi, string yayin_evi, string kitap_turu, string temin_bicimi, Nullable<System.DateTime> temin_tarihi, Nullable<int> stok_sayisi, string dosyayolu)
        {
            var barkodParameter = barkod != null ?
                new ObjectParameter("barkod", barkod) :
                new ObjectParameter("barkod", typeof(string));
    
            var kitap_adiParameter = kitap_adi != null ?
                new ObjectParameter("kitap_adi", kitap_adi) :
                new ObjectParameter("kitap_adi", typeof(string));
    
            var yazar_adiParameter = yazar_adi != null ?
                new ObjectParameter("yazar_adi", yazar_adi) :
                new ObjectParameter("yazar_adi", typeof(string));
    
            var yayin_eviParameter = yayin_evi != null ?
                new ObjectParameter("yayin_evi", yayin_evi) :
                new ObjectParameter("yayin_evi", typeof(string));
    
            var kitap_turuParameter = kitap_turu != null ?
                new ObjectParameter("kitap_turu", kitap_turu) :
                new ObjectParameter("kitap_turu", typeof(string));
    
            var temin_bicimiParameter = temin_bicimi != null ?
                new ObjectParameter("temin_bicimi", temin_bicimi) :
                new ObjectParameter("temin_bicimi", typeof(string));
    
            var temin_tarihiParameter = temin_tarihi.HasValue ?
                new ObjectParameter("temin_tarihi", temin_tarihi) :
                new ObjectParameter("temin_tarihi", typeof(System.DateTime));
    
            var stok_sayisiParameter = stok_sayisi.HasValue ?
                new ObjectParameter("stok_sayisi", stok_sayisi) :
                new ObjectParameter("stok_sayisi", typeof(int));
    
            var dosyayoluParameter = dosyayolu != null ?
                new ObjectParameter("dosyayolu", dosyayolu) :
                new ObjectParameter("dosyayolu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("kitapekleme", barkodParameter, kitap_adiParameter, yazar_adiParameter, yayin_eviParameter, kitap_turuParameter, temin_bicimiParameter, temin_tarihiParameter, stok_sayisiParameter, dosyayoluParameter);
        }
    
        public virtual int kisiekleme(Nullable<int> tc, string ad, string soyad, Nullable<int> okulno, string sinif, Nullable<System.DateTime> dogumtarihi, string dogumyeri, string tel, string eposta, Nullable<System.DateTime> uyeliktarih, string cinsiyet, string adres, string resimyolu)
        {
            var tcParameter = tc.HasValue ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(int));
    
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var soyadParameter = soyad != null ?
                new ObjectParameter("soyad", soyad) :
                new ObjectParameter("soyad", typeof(string));
    
            var okulnoParameter = okulno.HasValue ?
                new ObjectParameter("okulno", okulno) :
                new ObjectParameter("okulno", typeof(int));
    
            var sinifParameter = sinif != null ?
                new ObjectParameter("sinif", sinif) :
                new ObjectParameter("sinif", typeof(string));
    
            var dogumtarihiParameter = dogumtarihi.HasValue ?
                new ObjectParameter("dogumtarihi", dogumtarihi) :
                new ObjectParameter("dogumtarihi", typeof(System.DateTime));
    
            var dogumyeriParameter = dogumyeri != null ?
                new ObjectParameter("dogumyeri", dogumyeri) :
                new ObjectParameter("dogumyeri", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var epostaParameter = eposta != null ?
                new ObjectParameter("eposta", eposta) :
                new ObjectParameter("eposta", typeof(string));
    
            var uyeliktarihParameter = uyeliktarih.HasValue ?
                new ObjectParameter("uyeliktarih", uyeliktarih) :
                new ObjectParameter("uyeliktarih", typeof(System.DateTime));
    
            var cinsiyetParameter = cinsiyet != null ?
                new ObjectParameter("cinsiyet", cinsiyet) :
                new ObjectParameter("cinsiyet", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("adres", adres) :
                new ObjectParameter("adres", typeof(string));
    
            var resimyoluParameter = resimyolu != null ?
                new ObjectParameter("resimyolu", resimyolu) :
                new ObjectParameter("resimyolu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("kisiekleme", tcParameter, adParameter, soyadParameter, okulnoParameter, sinifParameter, dogumtarihiParameter, dogumyeriParameter, telParameter, epostaParameter, uyeliktarihParameter, cinsiyetParameter, adresParameter, resimyoluParameter);
        }
    
        public virtual ObjectResult<string> resimGetir(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("resimGetir", iDParameter);
        }
    
        public virtual ObjectResult<arama_Result> arama(string ad, string soyad, string sinif)
        {
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var soyadParameter = soyad != null ?
                new ObjectParameter("Soyad", soyad) :
                new ObjectParameter("Soyad", typeof(string));
    
            var sinifParameter = sinif != null ?
                new ObjectParameter("Sinif", sinif) :
                new ObjectParameter("Sinif", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<arama_Result>("arama", adParameter, soyadParameter, sinifParameter);
        }
    
        public virtual ObjectResult<aramaKitap_Result> aramaKitap(string barkodNo, string kitapAdi, string kitapYazari, string yayinEvi)
        {
            var barkodNoParameter = barkodNo != null ?
                new ObjectParameter("barkodNo", barkodNo) :
                new ObjectParameter("barkodNo", typeof(string));
    
            var kitapAdiParameter = kitapAdi != null ?
                new ObjectParameter("kitapAdi", kitapAdi) :
                new ObjectParameter("kitapAdi", typeof(string));
    
            var kitapYazariParameter = kitapYazari != null ?
                new ObjectParameter("kitapYazari", kitapYazari) :
                new ObjectParameter("kitapYazari", typeof(string));
    
            var yayinEviParameter = yayinEvi != null ?
                new ObjectParameter("yayinEvi", yayinEvi) :
                new ObjectParameter("yayinEvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<aramaKitap_Result>("aramaKitap", barkodNoParameter, kitapAdiParameter, kitapYazariParameter, yayinEviParameter);
        }
    
        public virtual int emanetkitapgetir(string ad, Nullable<int> okulNo, string kitapAdi, Nullable<System.DateTime> baslangicTarihi, Nullable<System.DateTime> bitisTarihi)
        {
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var okulNoParameter = okulNo.HasValue ?
                new ObjectParameter("okulNo", okulNo) :
                new ObjectParameter("okulNo", typeof(int));
    
            var kitapAdiParameter = kitapAdi != null ?
                new ObjectParameter("kitapAdi", kitapAdi) :
                new ObjectParameter("kitapAdi", typeof(string));
    
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("baslangicTarihi", baslangicTarihi) :
                new ObjectParameter("baslangicTarihi", typeof(System.DateTime));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("bitisTarihi", bitisTarihi) :
                new ObjectParameter("bitisTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("emanetkitapgetir", adParameter, okulNoParameter, kitapAdiParameter, baslangicTarihiParameter, bitisTarihiParameter);
        }
    
        public virtual int emanetkitapEkleme(string ad, string kitapAdi, Nullable<System.DateTime> baslangicTarihi, Nullable<System.DateTime> bitisTarihi, Nullable<int> okuduguKitap, Nullable<int> emanetKitap)
        {
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var kitapAdiParameter = kitapAdi != null ?
                new ObjectParameter("kitapAdi", kitapAdi) :
                new ObjectParameter("kitapAdi", typeof(string));
    
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("baslangicTarihi", baslangicTarihi) :
                new ObjectParameter("baslangicTarihi", typeof(System.DateTime));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("bitisTarihi", bitisTarihi) :
                new ObjectParameter("bitisTarihi", typeof(System.DateTime));
    
            var okuduguKitapParameter = okuduguKitap.HasValue ?
                new ObjectParameter("okuduguKitap", okuduguKitap) :
                new ObjectParameter("okuduguKitap", typeof(int));
    
            var emanetKitapParameter = emanetKitap.HasValue ?
                new ObjectParameter("emanetKitap", emanetKitap) :
                new ObjectParameter("emanetKitap", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("emanetkitapEkleme", adParameter, kitapAdiParameter, baslangicTarihiParameter, bitisTarihiParameter, okuduguKitapParameter, emanetKitapParameter);
        }
    
        public virtual ObjectResult<emanetArama_Result> emanetArama(string ad, string kitapAdi)
        {
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var kitapAdiParameter = kitapAdi != null ?
                new ObjectParameter("kitapAdi", kitapAdi) :
                new ObjectParameter("kitapAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<emanetArama_Result>("emanetArama", adParameter, kitapAdiParameter);
        }
    
        public virtual int emanetAramaDeneme(string ad, string kitapAdi, string yazarAdi)
        {
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var kitapAdiParameter = kitapAdi != null ?
                new ObjectParameter("kitapAdi", kitapAdi) :
                new ObjectParameter("kitapAdi", typeof(string));
    
            var yazarAdiParameter = yazarAdi != null ?
                new ObjectParameter("yazarAdi", yazarAdi) :
                new ObjectParameter("yazarAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("emanetAramaDeneme", adParameter, kitapAdiParameter, yazarAdiParameter);
        }
    
        public virtual ObjectResult<tumTablolarGetir_Result2> tumTablolarGetir(Nullable<int> no)
        {
            var noParameter = no.HasValue ?
                new ObjectParameter("no", no) :
                new ObjectParameter("no", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tumTablolarGetir_Result2>("tumTablolarGetir", noParameter);
        }
    
        public virtual int teslim(string adSoyad, string kitapAdi, Nullable<System.DateTime> teslimTarihi, string hasarDurum)
        {
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var kitapAdiParameter = kitapAdi != null ?
                new ObjectParameter("kitapAdi", kitapAdi) :
                new ObjectParameter("kitapAdi", typeof(string));
    
            var teslimTarihiParameter = teslimTarihi.HasValue ?
                new ObjectParameter("teslimTarihi", teslimTarihi) :
                new ObjectParameter("teslimTarihi", typeof(System.DateTime));
    
            var hasarDurumParameter = hasarDurum != null ?
                new ObjectParameter("hasarDurum", hasarDurum) :
                new ObjectParameter("hasarDurum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("teslim", adSoyadParameter, kitapAdiParameter, teslimTarihiParameter, hasarDurumParameter);
        }
    
        public virtual int teslimAlmaEmanetAzaltma(string ad, string kitapAdi)
        {
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var kitapAdiParameter = kitapAdi != null ?
                new ObjectParameter("kitapAdi", kitapAdi) :
                new ObjectParameter("kitapAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("teslimAlmaEmanetAzaltma", adParameter, kitapAdiParameter);
        }
    }
}
