//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneTakipSistemi
{
    using System;
    
    public partial class tumTablolarGetir_Result2
    {
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<int> okul_no { get; set; }
        public string kitap_adi { get; set; }
        public string yazar_adi { get; set; }
    }
}
